AWSTemplateFormatVersion: '2010-09-09'
Description: SQS OrderCreatedQueue Stack

Parameters:
  Environment:
    Type: String

Resources:
  OrderCreatedQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub OrderCreatedQueue-${Environment}
      VisibilityTimeout: 90

  SQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref OrderCreatedQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: sns.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt OrderCreatedQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:OrderCreatedTopic-${Environment}

Outputs:
  OrderCreatedQueue:
    Value: !Ref OrderCreatedQueue
  OrderCreatedQueueArn:
    Value: !GetAtt OrderCreatedQueue.Arn
