AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Invoice PDF Bucket Stack

Parameters:
  Environment:
    Type: String

Resources:
  InvoicePDFBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  InvoicePDFBucket:
    Value: !Ref InvoicePDFBucket
  InvoicePDFBucketArn:
    Value: !GetAtt InvoicePDFBucket.Arn
