AWSTemplateFormatVersion: '2010-09-09'
Description: S3 Product Images Bucket Stack with Notification Trigger

Parameters:
  Environment:
    Type: String
  ImageAnalyzerFunctionArn:
    Type: String

Resources:
  ProductImagesBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub product-images-bucket-${AWS::AccountId}-${Environment}
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !Ref ImageAnalyzerFunctionArn

Outputs:
  ProductImagesBucket:
    Value: !Ref ProductImagesBucket
  ProductImagesBucketArn:
    Value: !GetAtt ProductImagesBucket.Arn
