version = 0.1

[default.deploy.parameters]
stack_name = "hybrid-devops-serverless-prod"
resolve_s3 = true
s3_prefix = "hybrid-devops-serverless-prod"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"prod\""
image_repositories = []

[prod.deploy.parameters]
stack_name = "hybrid-devops-serverless-prod"
resolve_s3 = true
s3_prefix = "hybrid-devops-serverless-prod"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"prod\""
