AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: DynamoDB OrdersTable Stack

Parameters:
  Environment:
    Type: String

Resources:
  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub OrdersTable-${Environment}
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

Outputs:
  OrdersTable:
    Value: !Ref OrdersTable
  OrdersTableStreamArn:
    Value: !GetAtt OrdersTable.StreamArn
