AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Send Email Lambda Stack

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    Architectures:
      - x86_64

Parameters:
  Environment:
    Type: String
  SendEmailQueueArn:
    Type: String
  EmailNotificationTopicArn:
    Type: String

Resources:
  SendEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambdaHandler
      CodeUri: ../../src/send-email/
      Description: Process Send Email SQS message and trigger SES notifications.
      Environment:
        Variables:
          EMAIL_TOPIC_ARN: !Ref EmailNotificationTopicArn
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref EmailNotificationTopicArn
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: "*"
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !Ref SendEmailQueueArn
            BatchSize: 10

Outputs:
  SendEmailFunctionArn:
    Value: !GetAtt SendEmailFunction.Arn
