AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: WebSocket Handler Lambda Stack

Globals:
  Function:
    Timeout: 30
    Runtime: nodejs18.x
    Architectures:
      - x86_64

Parameters:
  Environment:
    Type: String
  WebSocketConnectionsTable:
    Type: String

Resources:
  WebSocketHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambdaHandler
      CodeUri: ../../src/websocket-handler/
      Description: Handle WebSocket connection lifecycle routes ($connect, $disconnect).
      Environment:
        Variables:
          CONNECTIONS_TABLE: !Ref WebSocketConnectionsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref WebSocketConnectionsTable

Outputs:
  WebSocketHandlerFunctionArn:
    Value: !GetAtt WebSocketHandlerFunction.Arn
  WebSocketHandlerFunctionArnGetAtt:
    Value: !GetAtt WebSocketHandlerFunction.Arn
